#!/usr/bin/env python3
"""
Extract single-quality variant URLs from Pluto TV master playlists.
Replaces adaptive master.m3u8 URLs with direct 720p variant playlist URLs.
Reads from output/plutotv_us.m3u8 (generated by index.js) and writes
to output/plutotv_us_720p.m3u8.
"""

import urllib.request
import sys
import re
import time

INPUT_FILE = "output/plutotv_us.m3u8"
OUTPUT_FILE = "output/plutotv_us_720p.m3u8"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

def fetch(url, retries=3):
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=10) as resp:
                return resp.read().decode("utf-8")
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(2)
            else:
                print(f"  Failed after {retries} attempts: {e}", file=sys.stderr)
                return None

def get_best_variant(master_url):
    content = fetch(master_url)
    if not content:
        return None
    try:
        lines = content.splitlines()
        variants = []
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.startswith("#EXT-X-STREAM-INF"):
                bw_match = re.search(r'BANDWIDTH=(\d+)', line)
                bandwidth = int(bw_match.group(1)) if bw_match else 0
                if i + 1 < len(lines):
                    variant_url = lines[i + 1].strip()
                    if variant_url and not variant_url.startswith("#"):
                        variants.append((bandwidth, variant_url))
                i += 2
            else:
                i += 1
        if not variants:
            return None
        variants.sort(key=lambda x: x[0], reverse=True)
        best_bandwidth, best_url = variants[0]
        if not best_url.startswith("http"):
            base_url = master_url.rsplit("/", 1)[0]
            best_url = f"{base_url}/{best_url}"
        return best_url
    except Exception as e:
        print(f"  Error parsing master playlist: {e}", file=sys.stderr)
        return None

def main():
    print(f"Reading {INPUT_FILE}...")
    with open(INPUT_FILE, "r") as f:
        lines = f.readlines()

    output_lines = []
    processed = 0
    failed = 0

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("#EXTINF"):
            output_lines.append(line)
            if i + 1 < len(lines):
                stream_url = lines[i + 1].strip()
                if stream_url.startswith("https://") and "master.m3u8" in stream_url:
                    name_match = re.search(r',\s*(.+)$', line.strip())
                    name = name_match.group(1) if name_match else "Unknown"
                    print(f"Processing: {name}")
                    variant_url = get_best_variant(stream_url)
                    if variant_url:
                        output_lines.append(variant_url + "\n")
                        processed += 1
                    else:
                        output_lines.append(lines[i + 1])
                        failed += 1
                        print(f"  Falling back to master URL")
                else:
                    output_lines.append(lines[i + 1])
                i += 2
            else:
                i += 1
        else:
            output_lines.append(line)
            i += 1

    with open(OUTPUT_FILE, "w") as f:
        f.writelines(output_lines)

    print(f"\nDone! Extracted: {processed}, Failed: {failed}")
    print(f"Output written to: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
